"""empty message

Revision ID: 5255b6c3a72f
Revises: None
Create Date: 2014-09-20 16:48:26.362748

"""

# revision identifiers, used by Alembic.
revision = '5255b6c3a72f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
